name: semantic -release
on: 
  pull_request:
    branches: 
      - main 
jobs: 
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/setup-python@v2
        with:

          python-version: ${{ matrix.python-version }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref : main
      - name: Semantic Release install
        run: |
          pip install python-semantic-release
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Semantic Release Publish
        run:  |
          semantic-release publish -v DEBUG

      